---
ahoyapi: v2

commands:
  up:
    usage: Build project.
    cmd: docker-compose up -d "$@"

  down:
    usage: Delete project.
    cmd: docker-compose down

  build:
    usage: Build project.
    cmd: docker-compose up -d --build "$@"

  ps:
    usage: List running Docker containers.
    cmd: docker-compose ps

  restart:
    usage: Restart Docker containers.
    cmd: docker-compose restart

  stop:
    usage: Stop Docker containers.
    cmd: docker-compose stop "$@"

  config:
    usage: Show Docker configs.
    cmd: docker-compose config

  logs:
    usage: Show Docker logs.
    cmd: docker-compose logs "$@"

  test:full:
    usage: Run full tests.
    cmd: |
      docker-compose exec -T test composer install
      docker-compose exec -T test php core/scripts/run-tests.sh --php /usr/local/bin/php --sqlite /tmp/drupal/test.sqlite --dburl mysql://root:root@mysql/drupal --url http://nginx:8080/ --all --color --verbose